### ISSUE TITLE
Checkpoint 3

### ISSUE THREAD

**Issue by mih9898** [mih9898/ent-java-movies-aggregator#5]
@pawaitemadisoncollege checkpoint 3 is ready. The project can be accessed at http://3.138.210.149:8080/movies_aggregator/
The updated version is still on main-dev-spring branch

If you can't access write me I will check.
Such delay was because of debugging issues.
The rest http://3.138.210.149:8080/movies_aggregator/api/movies can be accessed with username '2' and password '2'.
The above-mentioned user has ROLE_ADMIN and can access rest; all other registered have ROLE_USER.

The app will be able to save/delete movies for registered ones + refactoring
If I will be able to fix rest -- making search via rest (updating DB on go) then maybe I will try to replace java dao with js requests. If not then it will be fine with dao.

**Comment by pawaitemadisoncollege** [comment]
Hi @mih9898 - I'm glad to see you got this working!  I know you've been putting a lot of effort into this - tackling spring on your own is a big undertaking as you are finding out, but your hard work here will pay off!  Checkpoint 3 looks good!

- [ ] Is this search result expected? 
![Screen Shot 2021-03-31 at 7 51 59 AM](https://user-images.githubusercontent.com/13874466/113147450-6658a580-91f6-11eb-92e2-75cbcc04109c.png)

**Comment by mih9898** [comment]
Thanks.
Parser still improves. Now it supposes to be working
There was filter with <code>contains</code> but without <code>toLowerCase</code> that take away all results in some cases such as with word 'star'
